### ISSUE TITLE
Add 3.7-dev test

### ISSUE THREAD

**Issue by tseemann** [andrewjpage/tiptoft#12]
```
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

```

_Recent Python branches require OpenSSL 1.0.2+. As this library is not available for Trusty, 3.7, 3.7-dev, 3.8-dev, and nightly do not work (or use outdated archive)._

OR NOT ?

**Comment by andrewjpage** [comment]
It errors on 3.7-dev:
https://travis-ci.org/andrewjpage/tiptoft/jobs/436018316
