### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by conte1** [andrewjpage/tiptoft#25]
I realize this tool is designed for detecting plasmids, but I'm wondering if it could be modified for more general purposes such as detecting which samples had particular distinct sequences. There is surprisingly a lack of tools that do this using a kmer approach. 

I'm assuming it would not be as simple as providing these distinct sequences to the "--plasmid_data" parameter?

**Comment by andrewjpage** [comment]
Yes it should work with any FASTA file using the --plasmid_data parameter. It parses the header of the sequence something like "rep1.1_repE(pAMbeta1)_AF007787" and extracts out information to make the output pretty but you can of course repurpose it for your own needs. Let me know how you get along.  I've used the same fundamental method in Krocus https://github.com/andrewjpage/krocus for calling 7 MLST genes
